// banking-demo-ui/src/app/payments/payments-new/payments-new.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../service/api-service';
import { Observable } from 'rxjs';
import { BankAccount } from '../../model/bank-account';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-payments-new',
  templateUrl: './payments-new.component.html',
  styleUrl: './payments-new.component.scss'
})
export class PaymentsNewComponent {

  accounts: BankAccount[] = [];
  form = new FormGroup({
    account: new FormControl(this.accounts),
    targetName: new FormControl('', Validators.required),
    targetAccountNumber: new FormControl('', Validators.required),
    amount: new FormControl('', Validators.required),
    transferName: new FormControl('', Validators.required),
  })


  constructor(private apiService: ApiService) {}

  ngOnInit() {
    this.apiService.getAccounts()
    .subscribe({
      next: data => {
        this.accounts = data;
        
      },
      error: error=>{

      }
    })
    
    
    // .subscribe(data=>
      
      
    //   this.accounts=data);
  }

  submitForm() {
    console.log(this.form.value)
  }

}



<div class="containers">
    <div class="d-flex flex-column">

        <form [formGroup]="form" (submit)="$event.preventDefault(); submitForm()">

            <h1>Utwórz przelew krajowy</h1>
            Z rachunku:
            <select class="form-select mt-2" formControlName="account">
                <option *ngFor="let item of accounts " [ngValue]="item">
                    {{item.accountNumber}}
                </option>
            </select>

            <div class="row mt-2">
                <div class="col mt-2">
                    <div class="mb-3">
                        <label class="form-label">Nazwa odbiorcy</label>
                        <input class="form-control" type="text" formControlName="targetName">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Numer rachunku</label>
                        <input class="form-control" type="number" formControlName="targetAccountNumber">
                    </div>
                </div>
                <div class="col mt-2">
                    <div class="mb-3">
                        <label class="form-label">Kwota przelewu</label>
                        <input class="form-control" type="number" formControlName="amount">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Tytuł przelewu</label>
                        <input class="form-control" type="text" formControlName="transferName">
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-end align-items-center">
                <button class="btn btn-primary" type="submit"  [disabled]="form.invalid">Dalej</button>
            </div>
        </form>
    </div>
</div>

// banking-demo-webapp/src/frontend/vue/src/components/payments/PaymentsNew.vue
<template>
    <div class="container my-3">
        <div class="d-flex justify-content-center">
            <p class="lead">
                Utwórz przelew krajowy
            </p>
        </div>
        <form @submit.prevent="submitForm">
            <div class="row my-3">
                <div class="col-12 py-3">
                    <small>Z rachunku</small>
                    <select v-model="form.account" class="form-select">
                        <option v-for="account in accounts" :value="account">{{ account.accountNumber }}</option>
                    </select>

                </div>
                <div class="col-6 my-4 ">
                    <MDBInput label="Nazwa odbiorcy" v-model="form.targetName"
                        invalidFeedback="Please provide your first name" validFeedback="Looks good!"
                        validationEvent="input" required title="Must contain between 5 and 30 characters" minLength="5"
                        maxLength="30" />
                </div>
                <div class="col-6 my-4">
                    <MDBInput label="Numer rachunku" v-model="form.targetAccountNumber"
                        invalidFeedback="Please provide your first name" validFeedback="Looks good!"
                        validationEvent="input" required title="Must contain between 5 and 30 characters" minLength="5"
                        maxLength="30" />
                </div>
                <div class="col-6 my-4">
                    <MDBInput label="Kwota przelewu" v-model="form.amount"
                        invalidFeedback="Please provide your first name" validFeedback="Looks good!"
                        validationEvent="input" required title="Must contain between 5 and 30 characters" minLength="5"
                        maxLength="30" />
                </div>
                <div class="col-6 my-4">
                    <MDBInput label="Tytuł przelewu" v-model="form.transferName"
                        invalidFeedback="Please provide your first name" validFeedback="Looks good!"
                        validationEvent="input" required title="Must contain between 5 and 30 characters" minLength="5"
                        maxLength="30" />
                </div>
                <div class="col-12  my-2">
                    <div class="d-flex justify-content-end ">

                        <button class="btn btn-primary" type="submit">Dalej</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</template>

<script setup lang="ts">
import { MDBInput } from 'mdb-vue-ui-kit';
import { reactive } from 'vue';
import type { BankAccount } from '@/model/bank-account';

let accounts: BankAccount[] = [
    {
        accountName: "1",
        accountNumber: "2",
        availableBalance: 0,
        ledgerBalance: 0,
        accountType: "5",
    },
    {
        accountName: "3",
        accountNumber: "4",
        availableBalance: 0,
        ledgerBalance: 0,
        accountType: "6",
    }
];

const form = reactive({
    account:  accounts[0],
    targetName: null,
    targetAccountNumber: null,
    amount: null,
    transferName: null
})

function submitForm() {
    console.log('Dane formularza:', form);
}

</script>
